export const DEFAULT_GAME_KEY = "craving-spinner";

export const GAME_LIBRARY = [
  {
    key: "craving-spinner",
    slug: "craving-spinner",
    title: "Craving Spinner",
    description: "Spin through live restaurants and dishes when you cannot decide what to eat.",
    glyph: "01",
    mark: "Spin",
    shortTitle: "Spinner",
    group: "quick",
    crowd: "1P",
    homeHint: "One spin pick",
    actionHint: "Live spin",
    accent: "text-orange-700 bg-orange-50 border-orange-200",
    chip: "bg-orange-100 text-orange-700",
    softCard:
      "border-orange-200 bg-[linear-gradient(135deg,#fff7ed,#ffedd5_55%,#fff1f2)]",
    panel: "from-[#2f1408] via-[#7c2d12] to-[#c2410c]",
  },
  {
    key: "bite-catcher",
    slug: "bite-catcher",
    title: "Bite Catcher",
    description: "Catch falling bites, dodge hot trays, and chase a new best score.",
    glyph: "13",
    mark: "Catch",
    shortTitle: "Catcher",
    group: "quick",
    crowd: "1P",
    homeHint: "Full-screen arcade",
    actionHint: "Catch run",
    accent: "text-cyan-700 bg-cyan-50 border-cyan-200",
    chip: "bg-cyan-100 text-cyan-700",
    softCard:
      "border-cyan-200 bg-[linear-gradient(135deg,#ecfeff,#e0f2fe_55%,#fff7ed)]",
    panel: "from-[#07111f] via-[#0f766e] to-[#f97316]",
  },
  {
    key: "delivery-race",
    slug: "delivery-race",
    title: "Delivery Race",
    description: "Control a rider, dodge traffic, potholes, rain, and deliver faster for more coins.",
    glyph: "14",
    mark: "Race",
    shortTitle: "Race",
    group: "quick",
    crowd: "1P",
    homeHint: "Dodge and deliver",
    actionHint: "Start race",
    accent: "text-red-700 bg-red-50 border-red-200",
    chip: "bg-red-100 text-red-700",
    softCard: "border-red-200 bg-[linear-gradient(135deg,#fff1f2,#fee2e2_55%,#fff7ed)]",
    panel: "from-[#2b0909] via-[#991b1b] to-[#f97316]",
  },
  {
    key: "cook-combo",
    slug: "cook-combo",
    title: "Cook Combo",
    description: "Build burgers and pizzas under pressure. Correct ingredients grow your multiplier.",
    glyph: "15",
    mark: "Combo",
    shortTitle: "Combo",
    group: "quick",
    crowd: "1P",
    homeHint: "Stack the order",
    actionHint: "Cook fast",
    accent: "text-amber-700 bg-amber-50 border-amber-200",
    chip: "bg-amber-100 text-amber-800",
    softCard: "border-amber-200 bg-[linear-gradient(135deg,#fffbeb,#fef3c7_55%,#fff7ed)]",
    panel: "from-[#321300] via-[#b45309] to-[#f59e0b]",
  },
  {
    key: "hungry-monster",
    slug: "hungry-monster",
    title: "Hungry Monster",
    description: "Feed the daily monster correct food, keep hearts alive, and evolve it over streaks.",
    glyph: "16",
    mark: "Feed",
    shortTitle: "Monster",
    group: "daily",
    crowd: "1P",
    homeHint: "Daily evolve",
    actionHint: "Feed now",
    accent: "text-emerald-700 bg-emerald-50 border-emerald-200",
    chip: "bg-emerald-100 text-emerald-700",
    softCard: "border-emerald-200 bg-[linear-gradient(135deg,#ecfdf5,#d1fae5_55%,#fff7ed)]",
    panel: "from-[#052e16] via-[#15803d] to-[#f97316]",
  },
  {
    key: "coupon-hunt",
    slug: "coupon-hunt",
    title: "Coupon Hunt",
    description: "Find hidden coupons across menus, restaurant pages, carts, and daily missions.",
    glyph: "17",
    mark: "Hunt",
    shortTitle: "Hunt",
    group: "daily",
    crowd: "1P",
    homeHint: "Explore for coupons",
    actionHint: "Hunt",
    accent: "text-yellow-700 bg-yellow-50 border-yellow-200",
    chip: "bg-yellow-100 text-yellow-800",
    softCard: "border-yellow-200 bg-[linear-gradient(135deg,#fefce8,#fef9c3_55%,#fff7ed)]",
    panel: "from-[#2f2100] via-[#ca8a04] to-[#f97316]",
  },
  {
    key: "spin-battle",
    slug: "spin-battle",
    title: "Spin Battle",
    description: "Challenge a friend, spin together, and let the higher reward win bonus coins.",
    glyph: "18",
    mark: "VS",
    shortTitle: "Battle",
    group: "duo",
    crowd: "2P",
    homeHint: "Friend spin duel",
    actionHint: "Battle",
    accent: "text-fuchsia-700 bg-fuchsia-50 border-fuchsia-200",
    chip: "bg-fuchsia-100 text-fuchsia-700",
    softCard: "border-fuchsia-200 bg-[linear-gradient(135deg,#fdf4ff,#fae8ff_55%,#fff7ed)]",
    panel: "from-[#3b0764] via-[#a21caf] to-[#f97316]",
  },
  {
    key: "mystery-food-box",
    slug: "mystery-food-box",
    title: "Mystery Food Box",
    description: "Open loot boxes for coins, rare badges, coupons, free delivery, and mystery food.",
    glyph: "19",
    mark: "Box",
    shortTitle: "Mystery",
    group: "party",
    crowd: "1P",
    homeHint: "Open rare rewards",
    actionHint: "Open box",
    accent: "text-purple-700 bg-purple-50 border-purple-200",
    chip: "bg-purple-100 text-purple-700",
    softCard: "border-purple-200 bg-[linear-gradient(135deg,#faf5ff,#ede9fe_55%,#fff7ed)]",
    panel: "from-[#2e1065] via-[#7e22ce] to-[#f97316]",
  },
  {
    key: "chef-boss-fight",
    slug: "chef-boss-fight",
    title: "Chef Boss Fight",
    description: "Beat timed food quiz rounds and order combos to unlock legendary badges.",
    glyph: "20",
    mark: "Boss",
    shortTitle: "Boss",
    group: "brain",
    crowd: "1P",
    homeHint: "Timed boss quiz",
    actionHint: "Fight",
    accent: "text-stone-700 bg-stone-50 border-stone-200",
    chip: "bg-stone-900 text-white",
    softCard: "border-stone-200 bg-[linear-gradient(135deg,#f8fafc,#e7e5e4_55%,#fff7ed)]",
    panel: "from-[#0c0a09] via-[#44403c] to-[#f97316]",
  },
  {
    key: "food-snake",
    slug: "food-snake",
    title: "Food Snake",
    description: "Classic snake with burgers, pizzas, random coins, and escalating speed.",
    glyph: "21",
    mark: "Snake",
    shortTitle: "Snake",
    group: "quick",
    crowd: "1P",
    homeHint: "Eat and grow",
    actionHint: "Slither",
    accent: "text-lime-700 bg-lime-50 border-lime-200",
    chip: "bg-lime-100 text-lime-800",
    softCard: "border-lime-200 bg-[linear-gradient(135deg,#f7fee7,#ecfccb_55%,#fff7ed)]",
    panel: "from-[#1a2e05] via-[#65a30d] to-[#f97316]",
  },
  {
    key: "restaurant-empire",
    slug: "restaurant-empire",
    title: "Restaurant Empire",
    description: "Upgrade a stall into a cafe and restaurant chain for passive NearCoins.",
    glyph: "22",
    mark: "Idle",
    shortTitle: "Empire",
    group: "daily",
    crowd: "Idle",
    homeHint: "Build passive coins",
    actionHint: "Upgrade",
    accent: "text-teal-700 bg-teal-50 border-teal-200",
    chip: "bg-teal-100 text-teal-700",
    softCard: "border-teal-200 bg-[linear-gradient(135deg,#f0fdfa,#ccfbf1_55%,#fff7ed)]",
    panel: "from-[#042f2e] via-[#0f766e] to-[#f97316]",
  },
  {
    key: "blind-taste",
    slug: "blind-taste",
    title: "Blind Taste Challenge",
    description: "Guess the blurred dish. Correct streaks multiply XP and coupon odds.",
    glyph: "23",
    mark: "Guess",
    shortTitle: "Taste",
    group: "brain",
    crowd: "1P",
    homeHint: "Guess blurred food",
    actionHint: "Guess",
    accent: "text-sky-700 bg-sky-50 border-sky-200",
    chip: "bg-sky-100 text-sky-700",
    softCard: "border-sky-200 bg-[linear-gradient(135deg,#eff6ff,#dbeafe_55%,#fff7ed)]",
    panel: "from-[#082f49] via-[#0369a1] to-[#f97316]",
  },
  {
    key: "restaurant-duel",
    slug: "restaurant-duel",
    title: "Restaurant Duel",
    description: "Pick between real nearby restaurants and let your choices reveal a winner.",
    glyph: "02",
    mark: "VS",
    shortTitle: "Duel",
    group: "duo",
    crowd: "1P",
    homeHint: "Pick the winner",
    actionHint: "Face off",
    accent: "text-emerald-700 bg-emerald-50 border-emerald-200",
    chip: "bg-emerald-100 text-emerald-700",
    softCard:
      "border-emerald-200 bg-[linear-gradient(135deg,#ecfdf5,#d1fae5_55%,#effff7)]",
    panel: "from-[#052e24] via-[#065f46] to-[#10b981]",
  },
  {
    key: "food-memory",
    slug: "food-memory",
    title: "Food Memory",
    description: "Match real dishes and restaurants as fast as you can.",
    glyph: "03",
    mark: "Flip",
    shortTitle: "Memory",
    group: "brain",
    crowd: "1P",
    homeHint: "Flip and match",
    actionHint: "Memory race",
    accent: "text-sky-700 bg-sky-50 border-sky-200",
    chip: "bg-sky-100 text-sky-700",
    softCard:
      "border-sky-200 bg-[linear-gradient(135deg,#eff6ff,#dbeafe_55%,#ecfeff)]",
    panel: "from-[#082f49] via-[#0f4c81] to-[#2563eb]",
  },
  {
    key: "speed-quiz",
    slug: "speed-quiz",
    title: "Speed Quiz",
    description: "Answer quick questions from live restaurant ratings and delivery times.",
    glyph: "04",
    mark: "Quiz",
    shortTitle: "Quiz",
    group: "brain",
    crowd: "1P",
    homeHint: "Quick calls",
    actionHint: "Rapid quiz",
    accent: "text-violet-700 bg-violet-50 border-violet-200",
    chip: "bg-violet-100 text-violet-700",
    softCard:
      "border-violet-200 bg-[linear-gradient(135deg,#f5f3ff,#ede9fe_55%,#faf5ff)]",
    panel: "from-[#2e1065] via-[#6d28d9] to-[#8b5cf6]",
  },
  {
    key: "price-hunt",
    slug: "price-hunt",
    title: "Price Hunt",
    description: "Pick the best rated restaurant that still fits the shown budget.",
    glyph: "05",
    mark: "Budget",
    shortTitle: "Price",
    group: "quick",
    crowd: "1P",
    homeHint: "Budget chase",
    actionHint: "Value pick",
    accent: "text-amber-700 bg-amber-50 border-amber-200",
    chip: "bg-amber-100 text-amber-800",
    softCard:
      "border-amber-200 bg-[linear-gradient(135deg,#fffbeb,#fef3c7_55%,#fff7ed)]",
    panel: "from-[#3a1600] via-[#92400e] to-[#f59e0b]",
  },
  {
    key: "cuisine-match",
    slug: "cuisine-match",
    title: "Cuisine Match",
    description: "Match a craving or cuisine to the restaurant that actually serves it nearby.",
    glyph: "06",
    mark: "Match",
    shortTitle: "Cuisine",
    group: "brain",
    crowd: "1P",
    homeHint: "Spot the cuisine",
    actionHint: "Cuisine pick",
    accent: "text-rose-700 bg-rose-50 border-rose-200",
    chip: "bg-rose-100 text-rose-700",
    softCard:
      "border-rose-200 bg-[linear-gradient(135deg,#fff1f2,#ffe4e6_55%,#fff7ed)]",
    panel: "from-[#3f0c1b] via-[#9f1239] to-[#f43f5e]",
  },
  {
    key: "eta-rush",
    slug: "eta-rush",
    title: "ETA Rush",
    description: "Choose the fastest live option before the timer runs out.",
    glyph: "07",
    mark: "Rush",
    shortTitle: "ETA",
    group: "quick",
    crowd: "1P",
    homeHint: "Beat the clock",
    actionHint: "Fastest wins",
    accent: "text-cyan-700 bg-cyan-50 border-cyan-200",
    chip: "bg-cyan-100 text-cyan-700",
    softCard:
      "border-cyan-200 bg-[linear-gradient(135deg,#ecfeff,#cffafe_55%,#eff6ff)]",
    panel: "from-[#083344] via-[#0e7490] to-[#22d3ee]",
  },
  {
    key: "hand-cricket",
    slug: "hand-cricket",
    title: "Hand Cricket Night",
    description: "Pick 1 to 6, dodge the matching number, and survive a floodlit hand-cricket innings.",
    glyph: "08",
    mark: "1-6",
    shortTitle: "Cricket",
    group: "quick",
    crowd: "Bot",
    homeHint: "Number duel",
    actionHint: "Play ball",
    accent: "text-lime-700 bg-lime-50 border-lime-200",
    chip: "bg-lime-100 text-lime-800",
    softCard:
      "border-emerald-200 bg-[linear-gradient(135deg,#ecfeff,#dcfce7_55%,#fef3c7)]",
    panel: "from-[#03120d] via-[#047857] to-[#f59e0b]",
  },
  {
    key: "snakes-sprint",
    slug: "snake",
    title: "Snakes Sprint",
    description: "Race a bot across a quick snakes and ladders board.",
    glyph: "09",
    mark: "Race",
    shortTitle: "Snakes",
    group: "board",
    crowd: "Bot",
    homeHint: "Snake board race",
    actionHint: "Board sprint",
    accent: "text-fuchsia-700 bg-fuchsia-50 border-fuchsia-200",
    chip: "bg-fuchsia-100 text-fuchsia-700",
    softCard:
      "border-fuchsia-200 bg-[linear-gradient(135deg,#fdf4ff,#fae8ff_55%,#fce7f3)]",
    panel: "from-[#3b0764] via-[#a21caf] to-[#f472b6]",
  },
  {
    key: "snack-snap",
    slug: "snack-snap",
    title: "Snack Snap",
    description: "Tap the exact food match before the round timer runs out.",
    glyph: "10",
    mark: "Fast Tap",
    shortTitle: "Snap",
    group: "quick",
    crowd: "1P",
    homeHint: "Tap the twin",
    actionHint: "Fast tap",
    accent: "text-teal-700 bg-teal-50 border-teal-200",
    chip: "bg-teal-100 text-teal-700",
    softCard:
      "border-teal-200 bg-[linear-gradient(135deg,#f0fdfa,#ccfbf1_55%,#ecfeff)]",
    panel: "from-[#042f2e] via-[#0f766e] to-[#2dd4bf]",
  },
  {
    key: "tray-shuffle",
    slug: "tray-shuffle",
    title: "Tray Shuffle",
    description: "Track the hidden tray through fast shuffles and tap the right one.",
    glyph: "11",
    mark: "Track",
    shortTitle: "Shuffle",
    group: "brain",
    crowd: "1P",
    homeHint: "Track the tray",
    actionHint: "Watch closely",
    accent: "text-indigo-700 bg-indigo-50 border-indigo-200",
    chip: "bg-indigo-100 text-indigo-700",
    softCard:
      "border-indigo-200 bg-[linear-gradient(135deg,#eef2ff,#e0e7ff_55%,#f5f3ff)]",
    panel: "from-[#1e1b4b] via-[#4338ca] to-[#818cf8]",
  },
  {
    key: "lucky-tray",
    slug: "lucky-tray",
    title: "Lucky Tray",
    description: "Open bright food lids, dodge the zero, and build a lucky streak.",
    glyph: "12",
    mark: "Pick",
    shortTitle: "Lucky",
    group: "party",
    crowd: "1P",
    homeHint: "Open the lid",
    actionHint: "Lucky pick",
    accent: "text-pink-700 bg-pink-50 border-pink-200",
    chip: "bg-pink-100 text-pink-700",
    softCard:
      "border-pink-200 bg-[linear-gradient(135deg,#fdf2f8,#fce7f3_55%,#fff1f2)]",
    panel: "from-[#4a044e] via-[#be185d] to-[#fb7185]",
  },
];

export const GAME_THEME_BY_KEY = Object.fromEntries(
  GAME_LIBRARY.map((game) => [game.key, game])
);

export const GAME_OPTIONS = [
  { value: "any", label: "Any game" },
  ...GAME_LIBRARY.map((game) => ({ value: game.key, label: game.title })),
];

export const GAME_GROUPS = [
  { key: "all", label: "All" },
  { key: "quick", label: "Quick" },
  { key: "brain", label: "Brain" },
  { key: "daily", label: "Daily" },
  { key: "duo", label: "2P" },
  { key: "board", label: "Board" },
  { key: "party", label: "Lucky" },
];

export const getGameTheme = (gameKey) =>
  GAME_THEME_BY_KEY[gameKey] || GAME_THEME_BY_KEY[DEFAULT_GAME_KEY];

export const getGameSlug = (gameKey) =>
  GAME_THEME_BY_KEY[gameKey]?.slug || gameKey || DEFAULT_GAME_KEY;

export const getGameKeyFromSlug = (slug) => {
  const normalized = String(slug || "").toLowerCase();
  return (
    GAME_LIBRARY.find((game) => game.slug === normalized || game.key === normalized)
      ?.key || null
  );
};

export const withGameTheme = (game = {}) => {
  const theme = getGameTheme(game.key);
  return {
    ...theme,
    ...game,
    slug: getGameSlug(game.key),
    description: game.description || theme.description || theme.homeHint,
  };
};
